### ISSUE TITLE
Use lintr 3.0.0 Tag system

### ISSUE THREAD

**Issue by AshesITR** [Appsilon/box.linters#102]
The lintr 3.0.0 release introduced a new tag system to improve discoverability of linters from other packages.
Let me know if you would like to use the system and need help implementing it.

**Comment by radbasa** [comment]
Hello @AshesITR , thank you for your comment. Yes, tags would be a great addition to `box.linters` moving towards a version 1.0.0. 

Is it as simple as having the `inst/lintr/linters.csv` file in `box.linters`?

**Comment by AshesITR** [comment]
Hi @radbasa, that is correct.

The schema for the csv should match {lintr}, and the tags will be most useful if accompanied with documentation to help users see them, but this is not required.

Re-using tags from lintr (e.g., default) will also improve convenience.
