### ISSUE TITLE
[LINT_BUG]: `box_universal_import_linter` raises `box_trailing_commas_linter` if applied to the last `use` line.

### ISSUE THREAD

**Issue by pstorozenko** [Appsilon/box.linters#89]
### box.linters version

This is rhino 1.7.0

### Sample source code to lint

```
box::use(
  dplyr[...], # nolint: box_universal_import_linter.
)
```

### Lint command used

`rhino::lint_r()`

### Lint result

```
style: [box_trailing_commas_linter] Always have a trailing comma at the end of imports, before a `)`.
)
^
```

### Expected result

No error, as there is a trailing comma after `[...]`.
This may be a problem with other `nolint` and `box_universal_import_linter` is just an example.

**Comment by radbasa** [comment]
I see the problem.

`box_trailing_commas_linter()` works by finding the closing parenthesis `)` of a `box::use()` call. Then it goes back one element to check if a `OP-COMMA` exists. With a `# nolint: xyz`, however, it sees a `COMMENT` instead of an `OP-COMMA`.
